[[main]]
name = "about/"
url = "about"
weight = 10

[[main]]
name = "blog/"
url = "post"
weight = 20

[[main]]
name = "cv/"
url = "cv"
weight = 25

[[main]]
name = "notes/"
url = "notes/start-here"
weight = 30

#[[main]]
#  name = "books/"
#  url = "books"
#  weight = 35

[[main]]
name = "projects/"
url = "projects"
weight = 40

[[main]]
name = "@contact"
url = "contact"
weight = 60
